apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: kafka-consumer
  name: kafka-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - image: sha015/ms-2spring-kafka-consumer:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: ms-2spring-kafka-consumer
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: kafka-consumer
  name: kafka-consumer
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: kafka-consumer
  sessionAffinity: None
  type: LoadBalancer
